/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b1f0ce",
        "outline": "#9f8e7a",
        "surface-container": "#201f1f",
        "on-secondary-fixed-variant": "#6d3900",
        "surface-container-low": "#1c1b1b",
        "surface-bright": "#3a3939",
        "on-surface-variant": "#d7c3ae",
        "primary": "#ffc880",
        "on-tertiary-fixed-variant": "#0e5138",
        "primary-fixed": "#ffddb4",
        "tertiary-container": "#85c3a3",
        "on-tertiary": "#003824",
        "tertiary-fixed-dim": "#95d4b3",
        "on-background": "#e5e2e1",
        "background": "#131313",
        "secondary-fixed": "#ffdcc2",
        "on-surface": "#e5e2e1",
        "on-secondary-container": "#432100",
        "on-primary-fixed-variant": "#633f00",
        "surface-dim": "#131313",
        "on-primary-fixed": "#291800",
        "surface": "#131313",
        "secondary-container": "#d97807",
        "inverse-on-surface": "#313030",
        "secondary": "#ffb77c",
        "on-secondary": "#4d2700",
        "inverse-primary": "#835500",
        "surface-container-lowest": "#0e0e0e",
        "primary-container": "#f5a623",
        "surface-tint": "#ffb955",
        "on-secondary-fixed": "#2e1500",
        "primary-fixed-dim": "#ffb955",
        "on-error": "#690005",
        "on-tertiary-fixed": "#002114",
        "secondary-fixed-dim": "#ffb77c",
        "surface-container-highest": "#353534",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2a",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#644000",
        "on-primary": "#452b00",
        "outline-variant": "#524534",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#0f5138",
        "tertiary": "#a0dfbe",
        "surface-variant": "#353534"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
