/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b1f0ce",
        "outline": "#e2e8f0",
        "surface-container": "#e2e8f0",
        "on-secondary-fixed-variant": "#6d3900",
        "surface-container-low": "#f1f5f9",
        "surface-bright": "#ffffff",
        "on-surface-variant": "#475569",
        "primary": "#FF9100",
        "on-tertiary-fixed-variant": "#0e5138",
        "primary-fixed": "#ffe6c9",
        "tertiary-container": "#d1fae5",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#95d4b3",
        "on-background": "#0f172a",
        "background": "#f8fafc",
        "secondary-fixed": "#ffdcc2",
        "on-surface": "#0f172a",
        "on-secondary-container": "#0369a1",
        "on-primary-fixed-variant": "#633f00",
        "surface-dim": "#f1f5f9",
        "on-primary-fixed": "#291800",
        "surface": "#ffffff",
        "secondary-container": "#e0f2fe",
        "inverse-on-surface": "#f1f5f9",
        "secondary": "#0284c7",
        "on-secondary": "#ffffff",
        "inverse-primary": "#835500",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#FF9100",
        "surface-tint": "#FF9100",
        "on-secondary-fixed": "#2e1500",
        "primary-fixed-dim": "#ffa31a",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#002114",
        "secondary-fixed-dim": "#ffb77c",
        "surface-container-highest": "#94a3b8",
        "error-container": "#ffdad6",
        "surface-container-high": "#cbd5e1",
        "on-error-container": "#410002",
        "on-primary-container": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#cbd5e1",
        "error": "#ba1a1a",
        "inverse-surface": "#0f172a",
        "on-tertiary-container": "#065f46",
        "tertiary": "#10b981",
        "surface-variant": "#cbd5e1"
      },
      fontFamily: {
        "headline": ["Epilogue", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
      screens: {
        "xs": "480px",
      },
    },
  },
  plugins: [],
}
